traderShop = DawnInterface.addShop("shop2");
traderShop:addItem( itemDatabase["leynorscap"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["smallhealingpotion"] );
traderShop:addItem( itemDatabase["bladeofstrength"] );
traderShop:addItem( itemDatabase["bookofleatherskinrank2"] );
traderShop:loadShopkeeperInventory();