// config.h is generated by cmake while build freetype-gl from template config.h.in by cmake variable status

#define FREETYPE_GL_USE_GLEW 1
#define FREETYPE_GL_USE_VAO 1
/* #undef GL_WITH_GLAD */
